<MyGrid>
    GridLayout:
        cols: 1
        rows: 2
        size: root.width, root.height

        TextInput:
            id: screen
            size_hint: (1, .25)
            font_size: 55
            halign: "right"
        
        GridLayout:
            cols: 5

        #row 1

            Button:
		text: "7"
                font_size: 40
                on_press: root.pressed(7)

            Button:
		text: "8"
                font_size: 40
                on_press: root.pressed(8)

            Button:
		text: "9"
                font_size: 40
                on_press: root.pressed(9)

            Button:
		text: "x"
                font_size: 40
                on_press: root.operator("*")

            Button:
		text: "÷"
                font_size: 40
                on_press: root.operator("/")

        #row 2

            Button:
		text: "4"
                font_size: 40
                on_press: root.pressed(4)

            Button:
		text: "5"
                font_size: 40
                on_press: root.pressed(5)

            Button:
		text: "6"
                font_size: 40
                on_press: root.pressed(6)

            Button:
		text: "+"
                font_size: 40
                on_press: root.operator("+")

            Button:
		text: "-"
                font_size: 40
                on_press: root.operator("-")

        #row 3

	    Button:
		text: "1"
                font_size: 40
                on_press: root.pressed(1)

            Button:
		text: "2"
                font_size: 40
                on_press: root.pressed(2)

            Button:
		text: "3"
                font_size: 40
                on_press: root.pressed(3)

            Button:
                text: "%"
                font_size: 40
                on_press: root.operator("%")

            Button:
                text: "sin"
                font_size: 40
                on_press: root.math_f("sin")

        #row 4

	    Button:
		text: "0"
                font_size: 40
                on_press: root.pressed(0)

            Button:
                text: "C"
                font_size: 40
                on_press: root.clear()

            Button:
                text: "="
                font_size: 40
                on_press: root.result()

            Button:
                text : "cos"
                font_size: 40
                on_press: root.math_f("cos")

            Button:
                text : "tan"
                font_size: 40
                on_press: root.math_f("tan")
            
